### ISSUE TITLE
bug in firefox

### ISSUE THREAD

**Issue by evilebottnawi** [cloudfour/hideShowPassword#31]
![screenshot from 2015-05-22 15 03 17](https://cloud.githubusercontent.com/assets/4567934/7770145/bc019e4c-0093-11e5-80cc-b52b8ca47e4e.png)

**Comment by evilebottnawi** [comment]
fixed
```less
#user_pass {
    display: inline-block;
}
```
Firefox return display:inline, if display not set in styles
